/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Get dashboard summary
 */
export const GetDashboardResponse = zod.object({
  "totalCrops": zod.number(),
  "activeIrrigations": zod.number(),
  "pendingNotifications": zod.number(),
  "recentDetections": zod.array(zod.object({
  "id": zod.number(),
  "cropName": zod.string(),
  "imageUrl": zod.string().nullish(),
  "imageBase64": zod.string().nullish(),
  "diseaseName": zod.string().nullish(),
  "confidence": zod.number().nullish(),
  "severity": zod.string().nullish(),
  "symptoms": zod.string().nullish(),
  "organicTreatment": zod.string().nullish(),
  "chemicalTreatment": zod.string().nullish(),
  "fertilizerRecommendation": zod.string().nullish(),
  "preventiveMeasures": zod.string().nullish(),
  "recoveryTime": zod.string().nullish(),
  "aiResponse": zod.string().nullish(),
  "aiResponseTelugu": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})),
  "topMarketPrices": zod.array(zod.object({
  "id": zod.number(),
  "cropName": zod.string(),
  "mspPrice": zod.number().nullish(),
  "marketPrice": zod.number(),
  "unit": zod.string(),
  "market": zod.string(),
  "district": zod.string().nullish(),
  "state": zod.string().nullish(),
  "trend": zod.string().nullish(),
  "date": zod.coerce.date(),
  "createdAt": zod.coerce.date()
})),
  "monthlyExpenseTotal": zod.number(),
  "upcomingSchedules": zod.array(zod.object({
  "id": zod.number(),
  "cropId": zod.number().nullish(),
  "cropName": zod.string(),
  "scheduledAt": zod.coerce.date(),
  "durationMinutes": zod.number(),
  "waterAmount": zod.number().nullish(),
  "method": zod.string(),
  "status": zod.string(),
  "notes": zod.string().nullish(),
  "createdAt": zod.coerce.date()
}))
})


/**
 * @summary List all crops for the farm
 */
export const ListCropsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "variety": zod.string().nullish(),
  "season": zod.string(),
  "sowingDate": zod.coerce.date().nullish(),
  "harvestDate": zod.coerce.date().nullish(),
  "area": zod.number().nullish(),
  "areaUnit": zod.string().nullish(),
  "status": zod.string(),
  "notes": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})
export const ListCropsResponse = zod.array(ListCropsResponseItem)


/**
 * @summary Add a new crop
 */
export const CreateCropBody = zod.object({
  "name": zod.string(),
  "variety": zod.string().optional(),
  "season": zod.string(),
  "sowingDate": zod.coerce.date().optional(),
  "harvestDate": zod.coerce.date().optional(),
  "area": zod.number().optional(),
  "areaUnit": zod.string().optional(),
  "status": zod.string(),
  "notes": zod.string().optional()
})

export const CreateCropResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "variety": zod.string().nullish(),
  "season": zod.string(),
  "sowingDate": zod.coerce.date().nullish(),
  "harvestDate": zod.coerce.date().nullish(),
  "area": zod.number().nullish(),
  "areaUnit": zod.string().nullish(),
  "status": zod.string(),
  "notes": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get crop by ID
 */
export const GetCropParams = zod.object({
  "id": zod.coerce.number()
})

export const GetCropResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "variety": zod.string().nullish(),
  "season": zod.string(),
  "sowingDate": zod.coerce.date().nullish(),
  "harvestDate": zod.coerce.date().nullish(),
  "area": zod.number().nullish(),
  "areaUnit": zod.string().nullish(),
  "status": zod.string(),
  "notes": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Update a crop
 */
export const UpdateCropParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateCropBody = zod.object({
  "name": zod.string().optional(),
  "variety": zod.string().optional(),
  "season": zod.string().optional(),
  "sowingDate": zod.coerce.date().optional(),
  "harvestDate": zod.coerce.date().optional(),
  "area": zod.number().optional(),
  "areaUnit": zod.string().optional(),
  "status": zod.string().optional(),
  "notes": zod.string().optional()
})

export const UpdateCropResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "variety": zod.string().nullish(),
  "season": zod.string(),
  "sowingDate": zod.coerce.date().nullish(),
  "harvestDate": zod.coerce.date().nullish(),
  "area": zod.number().nullish(),
  "areaUnit": zod.string().nullish(),
  "status": zod.string(),
  "notes": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Delete a crop
 */
export const DeleteCropParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteCropResponse = zod.void()


/**
 * @summary List disease detection history
 */
export const ListDiseaseDetectionsResponseItem = zod.object({
  "id": zod.number(),
  "cropName": zod.string(),
  "imageUrl": zod.string().nullish(),
  "imageBase64": zod.string().nullish(),
  "diseaseName": zod.string().nullish(),
  "confidence": zod.number().nullish(),
  "severity": zod.string().nullish(),
  "symptoms": zod.string().nullish(),
  "organicTreatment": zod.string().nullish(),
  "chemicalTreatment": zod.string().nullish(),
  "fertilizerRecommendation": zod.string().nullish(),
  "preventiveMeasures": zod.string().nullish(),
  "recoveryTime": zod.string().nullish(),
  "aiResponse": zod.string().nullish(),
  "aiResponseTelugu": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})
export const ListDiseaseDetectionsResponse = zod.array(ListDiseaseDetectionsResponseItem)


/**
 * @summary Analyze crop image for disease using Gemini Vision
 */
export const CreateDiseaseDetectionBody = zod.object({
  "cropName": zod.string(),
  "imageBase64": zod.string(),
  "language": zod.string().optional()
})

export const CreateDiseaseDetectionResponse = zod.object({
  "id": zod.number(),
  "cropName": zod.string(),
  "imageUrl": zod.string().nullish(),
  "imageBase64": zod.string().nullish(),
  "diseaseName": zod.string().nullish(),
  "confidence": zod.number().nullish(),
  "severity": zod.string().nullish(),
  "symptoms": zod.string().nullish(),
  "organicTreatment": zod.string().nullish(),
  "chemicalTreatment": zod.string().nullish(),
  "fertilizerRecommendation": zod.string().nullish(),
  "preventiveMeasures": zod.string().nullish(),
  "recoveryTime": zod.string().nullish(),
  "aiResponse": zod.string().nullish(),
  "aiResponseTelugu": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get detection result
 */
export const GetDiseaseDetectionParams = zod.object({
  "id": zod.coerce.number()
})

export const GetDiseaseDetectionResponse = zod.object({
  "id": zod.number(),
  "cropName": zod.string(),
  "imageUrl": zod.string().nullish(),
  "imageBase64": zod.string().nullish(),
  "diseaseName": zod.string().nullish(),
  "confidence": zod.number().nullish(),
  "severity": zod.string().nullish(),
  "symptoms": zod.string().nullish(),
  "organicTreatment": zod.string().nullish(),
  "chemicalTreatment": zod.string().nullish(),
  "fertilizerRecommendation": zod.string().nullish(),
  "preventiveMeasures": zod.string().nullish(),
  "recoveryTime": zod.string().nullish(),
  "aiResponse": zod.string().nullish(),
  "aiResponseTelugu": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary List MSP and market prices
 */
export const ListMarketPricesResponseItem = zod.object({
  "id": zod.number(),
  "cropName": zod.string(),
  "mspPrice": zod.number().nullish(),
  "marketPrice": zod.number(),
  "unit": zod.string(),
  "market": zod.string(),
  "district": zod.string().nullish(),
  "state": zod.string().nullish(),
  "trend": zod.string().nullish(),
  "date": zod.coerce.date(),
  "createdAt": zod.coerce.date()
})
export const ListMarketPricesResponse = zod.array(ListMarketPricesResponseItem)


/**
 * @summary Add a market price entry
 */
export const CreateMarketPriceBody = zod.object({
  "cropName": zod.string(),
  "mspPrice": zod.number().optional(),
  "marketPrice": zod.number(),
  "unit": zod.string(),
  "market": zod.string(),
  "district": zod.string().optional(),
  "state": zod.string().optional(),
  "trend": zod.string().optional(),
  "date": zod.coerce.date()
})

export const CreateMarketPriceResponse = zod.object({
  "id": zod.number(),
  "cropName": zod.string(),
  "mspPrice": zod.number().nullish(),
  "marketPrice": zod.number(),
  "unit": zod.string(),
  "market": zod.string(),
  "district": zod.string().nullish(),
  "state": zod.string().nullish(),
  "trend": zod.string().nullish(),
  "date": zod.coerce.date(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get market summary with top movers and recommendations
 */
export const GetMarketSummaryResponse = zod.object({
  "topPrices": zod.array(zod.object({
  "id": zod.number(),
  "cropName": zod.string(),
  "mspPrice": zod.number().nullish(),
  "marketPrice": zod.number(),
  "unit": zod.string(),
  "market": zod.string(),
  "district": zod.string().nullish(),
  "state": zod.string().nullish(),
  "trend": zod.string().nullish(),
  "date": zod.coerce.date(),
  "createdAt": zod.coerce.date()
})),
  "trending": zod.array(zod.object({
  "id": zod.number(),
  "cropName": zod.string(),
  "mspPrice": zod.number().nullish(),
  "marketPrice": zod.number(),
  "unit": zod.string(),
  "market": zod.string(),
  "district": zod.string().nullish(),
  "state": zod.string().nullish(),
  "trend": zod.string().nullish(),
  "date": zod.coerce.date(),
  "createdAt": zod.coerce.date()
})),
  "averageMsp": zod.number(),
  "lastUpdated": zod.coerce.date()
})


/**
 * @summary List irrigation schedules
 */
export const ListIrrigationSchedulesResponseItem = zod.object({
  "id": zod.number(),
  "cropId": zod.number().nullish(),
  "cropName": zod.string(),
  "scheduledAt": zod.coerce.date(),
  "durationMinutes": zod.number(),
  "waterAmount": zod.number().nullish(),
  "method": zod.string(),
  "status": zod.string(),
  "notes": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})
export const ListIrrigationSchedulesResponse = zod.array(ListIrrigationSchedulesResponseItem)


/**
 * @summary Create irrigation schedule
 */
export const CreateIrrigationScheduleBody = zod.object({
  "cropId": zod.number().optional(),
  "cropName": zod.string(),
  "scheduledAt": zod.coerce.date(),
  "durationMinutes": zod.number(),
  "waterAmount": zod.number().optional(),
  "method": zod.string(),
  "status": zod.string(),
  "notes": zod.string().optional()
})

export const CreateIrrigationScheduleResponse = zod.object({
  "id": zod.number(),
  "cropId": zod.number().nullish(),
  "cropName": zod.string(),
  "scheduledAt": zod.coerce.date(),
  "durationMinutes": zod.number(),
  "waterAmount": zod.number().nullish(),
  "method": zod.string(),
  "status": zod.string(),
  "notes": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Update irrigation schedule
 */
export const UpdateIrrigationScheduleParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateIrrigationScheduleBody = zod.object({
  "scheduledAt": zod.coerce.date().optional(),
  "durationMinutes": zod.number().optional(),
  "waterAmount": zod.number().optional(),
  "method": zod.string().optional(),
  "status": zod.string().optional(),
  "notes": zod.string().optional()
})

export const UpdateIrrigationScheduleResponse = zod.object({
  "id": zod.number(),
  "cropId": zod.number().nullish(),
  "cropName": zod.string(),
  "scheduledAt": zod.coerce.date(),
  "durationMinutes": zod.number(),
  "waterAmount": zod.number().nullish(),
  "method": zod.string(),
  "status": zod.string(),
  "notes": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Delete irrigation schedule
 */
export const DeleteIrrigationScheduleParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteIrrigationScheduleResponse = zod.void()


/**
 * @summary List farm diary entries
 */
export const ListDiaryEntriesResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "content": zod.string(),
  "category": zod.string(),
  "cropId": zod.number().nullish(),
  "cropName": zod.string().nullish(),
  "weather": zod.string().nullish(),
  "temperature": zod.number().nullish(),
  "imageUrl": zod.string().nullish(),
  "entryDate": zod.coerce.date(),
  "createdAt": zod.coerce.date()
})
export const ListDiaryEntriesResponse = zod.array(ListDiaryEntriesResponseItem)


/**
 * @summary Create a diary entry
 */
export const CreateDiaryEntryBody = zod.object({
  "title": zod.string(),
  "content": zod.string(),
  "category": zod.string(),
  "cropId": zod.number().optional(),
  "cropName": zod.string().optional(),
  "weather": zod.string().optional(),
  "temperature": zod.number().optional(),
  "imageUrl": zod.string().optional(),
  "entryDate": zod.coerce.date()
})

export const CreateDiaryEntryResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "content": zod.string(),
  "category": zod.string(),
  "cropId": zod.number().nullish(),
  "cropName": zod.string().nullish(),
  "weather": zod.string().nullish(),
  "temperature": zod.number().nullish(),
  "imageUrl": zod.string().nullish(),
  "entryDate": zod.coerce.date(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get diary entry
 */
export const GetDiaryEntryParams = zod.object({
  "id": zod.coerce.number()
})

export const GetDiaryEntryResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "content": zod.string(),
  "category": zod.string(),
  "cropId": zod.number().nullish(),
  "cropName": zod.string().nullish(),
  "weather": zod.string().nullish(),
  "temperature": zod.number().nullish(),
  "imageUrl": zod.string().nullish(),
  "entryDate": zod.coerce.date(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Delete diary entry
 */
export const DeleteDiaryEntryParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteDiaryEntryResponse = zod.void()


/**
 * @summary List government schemes
 */
export const ListSchemesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string(),
  "category": zod.string(),
  "benefit": zod.string().nullish(),
  "eligibility": zod.string().nullish(),
  "applicationUrl": zod.string().nullish(),
  "deadline": zod.coerce.date().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.coerce.date()
})
export const ListSchemesResponse = zod.array(ListSchemesResponseItem)


/**
 * @summary Add a government scheme
 */
export const CreateSchemeBody = zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "category": zod.string(),
  "benefit": zod.string().optional(),
  "eligibility": zod.string().optional(),
  "applicationUrl": zod.string().optional(),
  "deadline": zod.coerce.date().optional(),
  "isActive": zod.boolean().optional()
})

export const CreateSchemeResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string(),
  "category": zod.string(),
  "benefit": zod.string().nullish(),
  "eligibility": zod.string().nullish(),
  "applicationUrl": zod.string().nullish(),
  "deadline": zod.coerce.date().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get scheme details
 */
export const GetSchemeParams = zod.object({
  "id": zod.coerce.number()
})

export const GetSchemeResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string(),
  "category": zod.string(),
  "benefit": zod.string().nullish(),
  "eligibility": zod.string().nullish(),
  "applicationUrl": zod.string().nullish(),
  "deadline": zod.coerce.date().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Update scheme
 */
export const UpdateSchemeParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateSchemeBody = zod.object({
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "category": zod.string().optional(),
  "benefit": zod.string().optional(),
  "eligibility": zod.string().optional(),
  "applicationUrl": zod.string().optional(),
  "deadline": zod.coerce.date().optional(),
  "isActive": zod.boolean().optional()
})

export const UpdateSchemeResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string(),
  "category": zod.string(),
  "benefit": zod.string().nullish(),
  "eligibility": zod.string().nullish(),
  "applicationUrl": zod.string().nullish(),
  "deadline": zod.coerce.date().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Delete scheme
 */
export const DeleteSchemeParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteSchemeResponse = zod.void()


/**
 * @summary List land marketplace listings
 */
export const ListLandListingsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string(),
  "listingType": zod.string(),
  "area": zod.number(),
  "areaUnit": zod.string(),
  "price": zod.number(),
  "priceUnit": zod.string(),
  "district": zod.string(),
  "village": zod.string().nullish(),
  "state": zod.string(),
  "soilType": zod.string().nullish(),
  "waterSource": zod.string().nullish(),
  "ownerName": zod.string(),
  "ownerPhone": zod.string().nullish(),
  "isVerified": zod.boolean(),
  "imageUrl": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})
export const ListLandListingsResponse = zod.array(ListLandListingsResponseItem)


/**
 * @summary Create a land listing
 */
export const CreateLandListingBody = zod.object({
  "title": zod.string(),
  "description": zod.string(),
  "listingType": zod.string(),
  "area": zod.number(),
  "areaUnit": zod.string(),
  "price": zod.number(),
  "priceUnit": zod.string(),
  "district": zod.string(),
  "village": zod.string().optional(),
  "state": zod.string(),
  "soilType": zod.string().optional(),
  "waterSource": zod.string().optional(),
  "ownerName": zod.string(),
  "ownerPhone": zod.string().optional(),
  "imageUrl": zod.string().optional()
})

export const CreateLandListingResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string(),
  "listingType": zod.string(),
  "area": zod.number(),
  "areaUnit": zod.string(),
  "price": zod.number(),
  "priceUnit": zod.string(),
  "district": zod.string(),
  "village": zod.string().nullish(),
  "state": zod.string(),
  "soilType": zod.string().nullish(),
  "waterSource": zod.string().nullish(),
  "ownerName": zod.string(),
  "ownerPhone": zod.string().nullish(),
  "isVerified": zod.boolean(),
  "imageUrl": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get land listing
 */
export const GetLandListingParams = zod.object({
  "id": zod.coerce.number()
})

export const GetLandListingResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string(),
  "listingType": zod.string(),
  "area": zod.number(),
  "areaUnit": zod.string(),
  "price": zod.number(),
  "priceUnit": zod.string(),
  "district": zod.string(),
  "village": zod.string().nullish(),
  "state": zod.string(),
  "soilType": zod.string().nullish(),
  "waterSource": zod.string().nullish(),
  "ownerName": zod.string(),
  "ownerPhone": zod.string().nullish(),
  "isVerified": zod.boolean(),
  "imageUrl": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Update land listing
 */
export const UpdateLandListingParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateLandListingBody = zod.object({
  "title": zod.string().optional(),
  "description": zod.string().optional(),
  "price": zod.number().optional(),
  "soilType": zod.string().optional(),
  "waterSource": zod.string().optional(),
  "isVerified": zod.boolean().optional(),
  "imageUrl": zod.string().optional()
})

export const UpdateLandListingResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string(),
  "listingType": zod.string(),
  "area": zod.number(),
  "areaUnit": zod.string(),
  "price": zod.number(),
  "priceUnit": zod.string(),
  "district": zod.string(),
  "village": zod.string().nullish(),
  "state": zod.string(),
  "soilType": zod.string().nullish(),
  "waterSource": zod.string().nullish(),
  "ownerName": zod.string(),
  "ownerPhone": zod.string().nullish(),
  "isVerified": zod.boolean(),
  "imageUrl": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Delete land listing
 */
export const DeleteLandListingParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteLandListingResponse = zod.void()


/**
 * @summary List community posts
 */
export const ListCommunityPostsResponseItem = zod.object({
  "id": zod.number(),
  "authorName": zod.string(),
  "authorRole": zod.string().nullish(),
  "title": zod.string(),
  "content": zod.string(),
  "category": zod.string(),
  "imageUrl": zod.string().nullish(),
  "likes": zod.number(),
  "tags": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})
export const ListCommunityPostsResponse = zod.array(ListCommunityPostsResponseItem)


/**
 * @summary Create community post
 */
export const CreateCommunityPostBody = zod.object({
  "authorName": zod.string(),
  "authorRole": zod.string().optional(),
  "title": zod.string(),
  "content": zod.string(),
  "category": zod.string(),
  "imageUrl": zod.string().optional(),
  "tags": zod.string().optional()
})

export const CreateCommunityPostResponse = zod.object({
  "id": zod.number(),
  "authorName": zod.string(),
  "authorRole": zod.string().nullish(),
  "title": zod.string(),
  "content": zod.string(),
  "category": zod.string(),
  "imageUrl": zod.string().nullish(),
  "likes": zod.number(),
  "tags": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get community post
 */
export const GetCommunityPostParams = zod.object({
  "id": zod.coerce.number()
})

export const GetCommunityPostResponse = zod.object({
  "id": zod.number(),
  "authorName": zod.string(),
  "authorRole": zod.string().nullish(),
  "title": zod.string(),
  "content": zod.string(),
  "category": zod.string(),
  "imageUrl": zod.string().nullish(),
  "likes": zod.number(),
  "tags": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Delete community post
 */
export const DeleteCommunityPostParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteCommunityPostResponse = zod.void()


/**
 * @summary Like a community post
 */
export const LikeCommunityPostParams = zod.object({
  "id": zod.coerce.number()
})

export const LikeCommunityPostResponse = zod.object({
  "id": zod.number(),
  "authorName": zod.string(),
  "authorRole": zod.string().nullish(),
  "title": zod.string(),
  "content": zod.string(),
  "category": zod.string(),
  "imageUrl": zod.string().nullish(),
  "likes": zod.number(),
  "tags": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary List expenses
 */
export const ListExpensesResponseItem = zod.object({
  "id": zod.number(),
  "category": zod.string(),
  "description": zod.string(),
  "amount": zod.number(),
  "date": zod.coerce.date(),
  "cropId": zod.number().nullish(),
  "cropName": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})
export const ListExpensesResponse = zod.array(ListExpensesResponseItem)


/**
 * @summary Add an expense
 */
export const CreateExpenseBody = zod.object({
  "category": zod.string(),
  "description": zod.string(),
  "amount": zod.number(),
  "date": zod.coerce.date(),
  "cropId": zod.number().optional(),
  "cropName": zod.string().optional()
})

export const CreateExpenseResponse = zod.object({
  "id": zod.number(),
  "category": zod.string(),
  "description": zod.string(),
  "amount": zod.number(),
  "date": zod.coerce.date(),
  "cropId": zod.number().nullish(),
  "cropName": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Delete an expense
 */
export const DeleteExpenseParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteExpenseResponse = zod.void()


/**
 * @summary Get expense summary by category
 */
export const GetExpenseSummaryResponse = zod.object({
  "totalAmount": zod.number(),
  "byCategory": zod.array(zod.object({
  "category": zod.string(),
  "total": zod.number()
})),
  "monthlyTotal": zod.number()
})


/**
 * @summary List soil analyses
 */
export const ListSoilAnalysesResponseItem = zod.object({
  "id": zod.number(),
  "ph": zod.number().nullish(),
  "nitrogen": zod.number().nullish(),
  "phosphorus": zod.number().nullish(),
  "potassium": zod.number().nullish(),
  "organicCarbon": zod.number().nullish(),
  "location": zod.string().nullish(),
  "cropId": zod.number().nullish(),
  "aiRecommendation": zod.string().nullish(),
  "fertilizerSchedule": zod.string().nullish(),
  "suitableCrops": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})
export const ListSoilAnalysesResponse = zod.array(ListSoilAnalysesResponseItem)


/**
 * @summary Submit soil analysis and get AI recommendations
 */
export const CreateSoilAnalysisBody = zod.object({
  "ph": zod.number().optional(),
  "nitrogen": zod.number().optional(),
  "phosphorus": zod.number().optional(),
  "potassium": zod.number().optional(),
  "organicCarbon": zod.number().optional(),
  "location": zod.string().optional(),
  "cropId": zod.number().optional()
})

export const CreateSoilAnalysisResponse = zod.object({
  "id": zod.number(),
  "ph": zod.number().nullish(),
  "nitrogen": zod.number().nullish(),
  "phosphorus": zod.number().nullish(),
  "potassium": zod.number().nullish(),
  "organicCarbon": zod.number().nullish(),
  "location": zod.string().nullish(),
  "cropId": zod.number().nullish(),
  "aiRecommendation": zod.string().nullish(),
  "fertilizerSchedule": zod.string().nullish(),
  "suitableCrops": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary List notifications
 */
export const ListNotificationsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "message": zod.string(),
  "type": zod.string(),
  "isRead": zod.boolean(),
  "createdAt": zod.coerce.date()
})
export const ListNotificationsResponse = zod.array(ListNotificationsResponseItem)


/**
 * @summary Mark notification as read
 */
export const MarkNotificationReadParams = zod.object({
  "id": zod.coerce.number()
})

export const MarkNotificationReadResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "message": zod.string(),
  "type": zod.string(),
  "isRead": zod.boolean(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Mark all notifications as read
 */
export const MarkAllNotificationsReadResponse = zod.object({
  "count": zod.number()
})


/**
 * @summary List all conversations
 */
export const ListGeminiConversationsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "createdAt": zod.coerce.date()
})
export const ListGeminiConversationsResponse = zod.array(ListGeminiConversationsResponseItem)


/**
 * @summary Create a new conversation
 */
export const CreateGeminiConversationBody = zod.object({
  "title": zod.string()
})

export const CreateGeminiConversationResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get conversation with messages
 */
export const GetGeminiConversationParams = zod.object({
  "id": zod.coerce.number()
})

export const GetGeminiConversationResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "createdAt": zod.coerce.date(),
  "messages": zod.array(zod.object({
  "id": zod.number(),
  "conversationId": zod.number(),
  "role": zod.string(),
  "content": zod.string(),
  "createdAt": zod.coerce.date()
}))
})


/**
 * @summary Delete a conversation
 */
export const DeleteGeminiConversationParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteGeminiConversationResponse = zod.void()


/**
 * @summary List messages in a conversation
 */
export const ListGeminiMessagesParams = zod.object({
  "id": zod.coerce.number()
})

export const ListGeminiMessagesResponseItem = zod.object({
  "id": zod.number(),
  "conversationId": zod.number(),
  "role": zod.string(),
  "content": zod.string(),
  "createdAt": zod.coerce.date()
})
export const ListGeminiMessagesResponse = zod.array(ListGeminiMessagesResponseItem)


/**
 * @summary Send a message and receive an AI response (SSE stream)
 */
export const SendGeminiMessageParams = zod.object({
  "id": zod.coerce.number()
})

export const SendGeminiMessageBody = zod.object({
  "content": zod.string()
})

export const SendGeminiMessageResponse = zod.unknown()


/**
 * @summary Generate an image from a text prompt
 */
export const GenerateGeminiImageBody = zod.object({
  "prompt": zod.string()
})

export const GenerateGeminiImageResponse = zod.object({
  "b64_json": zod.string(),
  "mimeType": zod.string()
})


