/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface BulkUpdateResult {
  count: number;
}

export interface DiseaseDetection {
  id: number;
  cropName: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  imageBase64?: string | null;
  /** @nullable */
  diseaseName?: string | null;
  /** @nullable */
  confidence?: number | null;
  /** @nullable */
  severity?: string | null;
  /** @nullable */
  symptoms?: string | null;
  /** @nullable */
  organicTreatment?: string | null;
  /** @nullable */
  chemicalTreatment?: string | null;
  /** @nullable */
  fertilizerRecommendation?: string | null;
  /** @nullable */
  preventiveMeasures?: string | null;
  /** @nullable */
  recoveryTime?: string | null;
  /** @nullable */
  aiResponse?: string | null;
  /** @nullable */
  aiResponseTelugu?: string | null;
  createdAt: string;
}

export interface MarketPrice {
  id: number;
  cropName: string;
  /** @nullable */
  mspPrice?: number | null;
  marketPrice: number;
  unit: string;
  market: string;
  /** @nullable */
  district?: string | null;
  /** @nullable */
  state?: string | null;
  /** @nullable */
  trend?: string | null;
  date: string;
  createdAt: string;
}

export interface IrrigationSchedule {
  id: number;
  /** @nullable */
  cropId?: number | null;
  cropName: string;
  scheduledAt: string;
  durationMinutes: number;
  /** @nullable */
  waterAmount?: number | null;
  method: string;
  status: string;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
}

export interface DashboardSummary {
  totalCrops: number;
  activeIrrigations: number;
  pendingNotifications: number;
  recentDetections: DiseaseDetection[];
  topMarketPrices: MarketPrice[];
  monthlyExpenseTotal: number;
  upcomingSchedules: IrrigationSchedule[];
}

export interface Crop {
  id: number;
  name: string;
  /** @nullable */
  variety?: string | null;
  season: string;
  /** @nullable */
  sowingDate?: string | null;
  /** @nullable */
  harvestDate?: string | null;
  /** @nullable */
  area?: number | null;
  /** @nullable */
  areaUnit?: string | null;
  status: string;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
}

export interface CropInput {
  name: string;
  variety?: string;
  season: string;
  sowingDate?: string;
  harvestDate?: string;
  area?: number;
  areaUnit?: string;
  status: string;
  notes?: string;
}

export interface CropUpdate {
  name?: string;
  variety?: string;
  season?: string;
  sowingDate?: string;
  harvestDate?: string;
  area?: number;
  areaUnit?: string;
  status?: string;
  notes?: string;
}

export interface DiseaseDetectionInput {
  cropName: string;
  imageBase64: string;
  language?: string;
}

export interface MarketPriceInput {
  cropName: string;
  mspPrice?: number;
  marketPrice: number;
  unit: string;
  market: string;
  district?: string;
  state?: string;
  trend?: string;
  date: string;
}

export interface MarketSummary {
  topPrices: MarketPrice[];
  trending: MarketPrice[];
  averageMsp: number;
  lastUpdated: string;
}

export interface IrrigationScheduleInput {
  cropId?: number;
  cropName: string;
  scheduledAt: string;
  durationMinutes: number;
  waterAmount?: number;
  method: string;
  status: string;
  notes?: string;
}

export interface IrrigationScheduleUpdate {
  scheduledAt?: string;
  durationMinutes?: number;
  waterAmount?: number;
  method?: string;
  status?: string;
  notes?: string;
}

export interface DiaryEntry {
  id: number;
  title: string;
  content: string;
  category: string;
  /** @nullable */
  cropId?: number | null;
  /** @nullable */
  cropName?: string | null;
  /** @nullable */
  weather?: string | null;
  /** @nullable */
  temperature?: number | null;
  /** @nullable */
  imageUrl?: string | null;
  entryDate: string;
  createdAt: string;
}

export interface DiaryEntryInput {
  title: string;
  content: string;
  category: string;
  cropId?: number;
  cropName?: string;
  weather?: string;
  temperature?: number;
  imageUrl?: string;
  entryDate: string;
}

export interface GovernmentScheme {
  id: number;
  name: string;
  description: string;
  category: string;
  /** @nullable */
  benefit?: string | null;
  /** @nullable */
  eligibility?: string | null;
  /** @nullable */
  applicationUrl?: string | null;
  /** @nullable */
  deadline?: string | null;
  isActive: boolean;
  createdAt: string;
}

export interface GovernmentSchemeInput {
  name: string;
  description: string;
  category: string;
  benefit?: string;
  eligibility?: string;
  applicationUrl?: string;
  deadline?: string;
  isActive?: boolean;
}

export interface GovernmentSchemeUpdate {
  name?: string;
  description?: string;
  category?: string;
  benefit?: string;
  eligibility?: string;
  applicationUrl?: string;
  deadline?: string;
  isActive?: boolean;
}

export interface LandListing {
  id: number;
  title: string;
  description: string;
  listingType: string;
  area: number;
  areaUnit: string;
  price: number;
  priceUnit: string;
  district: string;
  /** @nullable */
  village?: string | null;
  state: string;
  /** @nullable */
  soilType?: string | null;
  /** @nullable */
  waterSource?: string | null;
  ownerName: string;
  /** @nullable */
  ownerPhone?: string | null;
  isVerified: boolean;
  /** @nullable */
  imageUrl?: string | null;
  createdAt: string;
}

export interface LandListingInput {
  title: string;
  description: string;
  listingType: string;
  area: number;
  areaUnit: string;
  price: number;
  priceUnit: string;
  district: string;
  village?: string;
  state: string;
  soilType?: string;
  waterSource?: string;
  ownerName: string;
  ownerPhone?: string;
  imageUrl?: string;
}

export interface LandListingUpdate {
  title?: string;
  description?: string;
  price?: number;
  soilType?: string;
  waterSource?: string;
  isVerified?: boolean;
  imageUrl?: string;
}

export interface CommunityPost {
  id: number;
  authorName: string;
  /** @nullable */
  authorRole?: string | null;
  title: string;
  content: string;
  category: string;
  /** @nullable */
  imageUrl?: string | null;
  likes: number;
  /** @nullable */
  tags?: string | null;
  createdAt: string;
}

export interface CommunityPostInput {
  authorName: string;
  authorRole?: string;
  title: string;
  content: string;
  category: string;
  imageUrl?: string;
  tags?: string;
}

export interface Expense {
  id: number;
  category: string;
  description: string;
  amount: number;
  date: string;
  /** @nullable */
  cropId?: number | null;
  /** @nullable */
  cropName?: string | null;
  createdAt: string;
}

export interface ExpenseInput {
  category: string;
  description: string;
  amount: number;
  date: string;
  cropId?: number;
  cropName?: string;
}

export interface ExpenseCategoryTotal {
  category: string;
  total: number;
}

export interface ExpenseSummary {
  totalAmount: number;
  byCategory: ExpenseCategoryTotal[];
  monthlyTotal: number;
}

export interface SoilAnalysis {
  id: number;
  /** @nullable */
  ph?: number | null;
  /** @nullable */
  nitrogen?: number | null;
  /** @nullable */
  phosphorus?: number | null;
  /** @nullable */
  potassium?: number | null;
  /** @nullable */
  organicCarbon?: number | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  cropId?: number | null;
  /** @nullable */
  aiRecommendation?: string | null;
  /** @nullable */
  fertilizerSchedule?: string | null;
  /** @nullable */
  suitableCrops?: string | null;
  createdAt: string;
}

export interface SoilAnalysisInput {
  ph?: number;
  nitrogen?: number;
  phosphorus?: number;
  potassium?: number;
  organicCarbon?: number;
  location?: string;
  cropId?: number;
}

export interface Notification {
  id: number;
  title: string;
  message: string;
  type: string;
  isRead: boolean;
  createdAt: string;
}

export interface GeminiConversation {
  id: number;
  title: string;
  createdAt: string;
}

export interface GeminiMessage {
  id: number;
  conversationId: number;
  role: string;
  content: string;
  createdAt: string;
}

export interface GeminiConversationInput {
  title: string;
}

export interface GeminiMessageInput {
  content: string;
}

export interface GeminiConversationWithMessages {
  id: number;
  title: string;
  createdAt: string;
  messages: GeminiMessage[];
}

export interface GeminiImageInput {
  prompt: string;
}

export interface GeminiImageOutput {
  b64_json: string;
  mimeType: string;
}

export interface GeminiError {
  error: string;
}

