/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface CommunityPostInput {
    authorName: string;
    authorRole?: string;
    title: string;
    content: string;
    category: string;
    imageUrl?: string;
    tags?: string;
}
//# sourceMappingURL=communityPostInput.d.ts.map