/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */

export interface CommunityPost {
  id: number;
  authorName: string;
  /** @nullable */
  authorRole?: string | null;
  title: string;
  content: string;
  category: string;
  /** @nullable */
  imageUrl?: string | null;
  likes: number;
  /** @nullable */
  tags?: string | null;
  createdAt: Date;
}
