/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface CropInput {
    name: string;
    variety?: string;
    season: string;
    sowingDate?: Date;
    harvestDate?: Date;
    area?: number;
    areaUnit?: string;
    status: string;
    notes?: string;
}
//# sourceMappingURL=cropInput.d.ts.map