/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface Crop {
    id: number;
    name: string;
    /** @nullable */
    variety?: string | null;
    season: string;
    /** @nullable */
    sowingDate?: Date | null;
    /** @nullable */
    harvestDate?: Date | null;
    /** @nullable */
    area?: number | null;
    /** @nullable */
    areaUnit?: string | null;
    status: string;
    /** @nullable */
    notes?: string | null;
    createdAt: Date;
}
//# sourceMappingURL=crop.d.ts.map