/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
import type { DiseaseDetection } from './diseaseDetection';
import type { IrrigationSchedule } from './irrigationSchedule';
import type { MarketPrice } from './marketPrice';

export interface DashboardSummary {
  totalCrops: number;
  activeIrrigations: number;
  pendingNotifications: number;
  recentDetections: DiseaseDetection[];
  topMarketPrices: MarketPrice[];
  monthlyExpenseTotal: number;
  upcomingSchedules: IrrigationSchedule[];
}
