/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface DiaryEntryInput {
    title: string;
    content: string;
    category: string;
    cropId?: number;
    cropName?: string;
    weather?: string;
    temperature?: number;
    imageUrl?: string;
    entryDate: Date;
}
//# sourceMappingURL=diaryEntryInput.d.ts.map