/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */

export interface DiaryEntry {
  id: number;
  title: string;
  content: string;
  category: string;
  /** @nullable */
  cropId?: number | null;
  /** @nullable */
  cropName?: string | null;
  /** @nullable */
  weather?: string | null;
  /** @nullable */
  temperature?: number | null;
  /** @nullable */
  imageUrl?: string | null;
  entryDate: Date;
  createdAt: Date;
}
