/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface DiseaseDetection {
    id: number;
    cropName: string;
    /** @nullable */
    imageUrl?: string | null;
    /** @nullable */
    imageBase64?: string | null;
    /** @nullable */
    diseaseName?: string | null;
    /** @nullable */
    confidence?: number | null;
    /** @nullable */
    severity?: string | null;
    /** @nullable */
    symptoms?: string | null;
    /** @nullable */
    organicTreatment?: string | null;
    /** @nullable */
    chemicalTreatment?: string | null;
    /** @nullable */
    fertilizerRecommendation?: string | null;
    /** @nullable */
    preventiveMeasures?: string | null;
    /** @nullable */
    recoveryTime?: string | null;
    /** @nullable */
    aiResponse?: string | null;
    /** @nullable */
    aiResponseTelugu?: string | null;
    createdAt: Date;
}
//# sourceMappingURL=diseaseDetection.d.ts.map