/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
import type { ExpenseCategoryTotal } from './expenseCategoryTotal';

export interface ExpenseSummary {
  totalAmount: number;
  byCategory: ExpenseCategoryTotal[];
  monthlyTotal: number;
}
