/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface ExpenseInput {
    category: string;
    description: string;
    amount: number;
    date: Date;
    cropId?: number;
    cropName?: string;
}
//# sourceMappingURL=expenseInput.d.ts.map