/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */

export interface Expense {
  id: number;
  category: string;
  description: string;
  amount: number;
  date: Date;
  /** @nullable */
  cropId?: number | null;
  /** @nullable */
  cropName?: string | null;
  createdAt: Date;
}
