/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface ExpenseCategoryTotal {
    category: string;
    total: number;
}
//# sourceMappingURL=expenseCategoryTotal.d.ts.map