/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */

export interface GovernmentScheme {
  id: number;
  name: string;
  description: string;
  category: string;
  /** @nullable */
  benefit?: string | null;
  /** @nullable */
  eligibility?: string | null;
  /** @nullable */
  applicationUrl?: string | null;
  /** @nullable */
  deadline?: Date | null;
  isActive: boolean;
  createdAt: Date;
}
