/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface GovernmentSchemeInput {
    name: string;
    description: string;
    category: string;
    benefit?: string;
    eligibility?: string;
    applicationUrl?: string;
    deadline?: Date;
    isActive?: boolean;
}
//# sourceMappingURL=governmentSchemeInput.d.ts.map