/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface IrrigationScheduleInput {
    cropId?: number;
    cropName: string;
    scheduledAt: Date;
    durationMinutes: number;
    waterAmount?: number;
    method: string;
    status: string;
    notes?: string;
}
//# sourceMappingURL=irrigationScheduleInput.d.ts.map