/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface IrrigationSchedule {
    id: number;
    /** @nullable */
    cropId?: number | null;
    cropName: string;
    scheduledAt: Date;
    durationMinutes: number;
    /** @nullable */
    waterAmount?: number | null;
    method: string;
    status: string;
    /** @nullable */
    notes?: string | null;
    createdAt: Date;
}
//# sourceMappingURL=irrigationSchedule.d.ts.map