/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface LandListing {
    id: number;
    title: string;
    description: string;
    listingType: string;
    area: number;
    areaUnit: string;
    price: number;
    priceUnit: string;
    district: string;
    /** @nullable */
    village?: string | null;
    state: string;
    /** @nullable */
    soilType?: string | null;
    /** @nullable */
    waterSource?: string | null;
    ownerName: string;
    /** @nullable */
    ownerPhone?: string | null;
    isVerified: boolean;
    /** @nullable */
    imageUrl?: string | null;
    createdAt: Date;
}
//# sourceMappingURL=landListing.d.ts.map