/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface LandListingUpdate {
    title?: string;
    description?: string;
    price?: number;
    soilType?: string;
    waterSource?: string;
    isVerified?: boolean;
    imageUrl?: string;
}
//# sourceMappingURL=landListingUpdate.d.ts.map