/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface LandListingInput {
    title: string;
    description: string;
    listingType: string;
    area: number;
    areaUnit: string;
    price: number;
    priceUnit: string;
    district: string;
    village?: string;
    state: string;
    soilType?: string;
    waterSource?: string;
    ownerName: string;
    ownerPhone?: string;
    imageUrl?: string;
}
//# sourceMappingURL=landListingInput.d.ts.map