/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface MarketPrice {
    id: number;
    cropName: string;
    /** @nullable */
    mspPrice?: number | null;
    marketPrice: number;
    unit: string;
    market: string;
    /** @nullable */
    district?: string | null;
    /** @nullable */
    state?: string | null;
    /** @nullable */
    trend?: string | null;
    date: Date;
    createdAt: Date;
}
//# sourceMappingURL=marketPrice.d.ts.map