/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
export interface MarketPriceInput {
    cropName: string;
    mspPrice?: number;
    marketPrice: number;
    unit: string;
    market: string;
    district?: string;
    state?: string;
    trend?: string;
    date: Date;
}
//# sourceMappingURL=marketPriceInput.d.ts.map