/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */
import type { MarketPrice } from './marketPrice';

export interface MarketSummary {
  topPrices: MarketPrice[];
  trending: MarketPrice[];
  averageMsp: number;
  lastUpdated: Date;
}
