/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * AgriSmart API
 * OpenAPI spec version: 0.1.0
 */

export interface SoilAnalysis {
  id: number;
  /** @nullable */
  ph?: number | null;
  /** @nullable */
  nitrogen?: number | null;
  /** @nullable */
  phosphorus?: number | null;
  /** @nullable */
  potassium?: number | null;
  /** @nullable */
  organicCarbon?: number | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  cropId?: number | null;
  /** @nullable */
  aiRecommendation?: string | null;
  /** @nullable */
  fertilizerSchedule?: string | null;
  /** @nullable */
  suitableCrops?: string | null;
  createdAt: Date;
}
